# /nsm-cpp-engine/grafana/provisioning/datasources/loki-datasource.yaml
apiVersion: 1

datasources:
  - name: Loki-Findings
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
    editable: true
