server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug  # ✅ Changed to debug for troubleshooting

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    timeout: 30s
    batchwait: 5s
    batchsize: 102400  # 100KB
    backoff_config:
      min_period: 500ms
      max_period: 10s
      max_retries: 10

scrape_configs:
  - job_name: corr-engine-findings
    static_configs:
      - targets:
          - localhost
        labels:
          job: corr-engine-findings
          source: correlation-engine
          __path__: /findings/findings.json
    
    pipeline_stages:
      # Parse JSON
      - json:
          expressions:
            timestamp: timestamp
            rule_name: rule_name
            correlation_id: correlation_id
            src_ip: original_event.src_ip
            dest_ip: original_event.dest_ip
      
      # Extract labels (EXCLUDE correlation_id - too high cardinality)
      - labels:
          rule_name:
      
      # Parse timestamp with CORRECTED format
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000000-0700"  # ✅ FIXED
          fallback_formats:
            - "2006-01-02T15:04:05Z0700"
            - "2006-01-02T15:04:05.999999999Z07:00"
            - "RFC3339"
      
      # Output for debugging
      - output:
          source: timestamp

  - job_name: suricata-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: suricata-logs
          source: suricata
          __path__: /var/log/suricata/eve.json
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            event_type: event_type
            src_ip: src_ip
            dest_ip: dest_ip
            alert_signature: alert.signature
            alert_severity: alert.severity
      
      - labels:
          event_type:
      
      # Drop non-alert events
      - match:
          selector: '{job="suricata-logs", event_type!="alert"}'
          action: drop
      
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000000-0700"
          fallback_formats:
            - "2006-01-02T15:04:05Z0700"
            - "RFC3339"
