server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    timeout: 30s
    batchwait: 5s
    batchsize: 102400
    backoff_config:
      min_period: 500ms
      max_period: 10s
      max_retries: 10

scrape_configs:
  - job_name: corr-engine-findings
    static_configs:
      - targets: [localhost]
        labels:
          job: corr-engine-findings
          source: correlation-engine
          correlation: "true"
          __path__: /findings/findings.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            rule_name: rule_name
      - labels:
          rule_name:
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000000+0000"
          fallback_formats:
            - "2006-01-02T15:04:05.000000-0700"
            - "2006-01-02T15:04:05Z0700"
            - "2006-01-02T15:04:05.999999999Z07:00"
            - "RFC3339"
          action_on_failure: fudge
  - job_name: suricata-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: suricata-logs
          source: suricata
          __path__: /var/log/suricata/eve.json
    pipeline_stages:
      - json:
          expressions:
            event_type: event_type
            timestamp: timestamp
            src_ip: src_ip
            dest_ip: dest_ip
            alert_signature: alert.signature
            alert_category: alert.category
            alert_severity: alert.severity
          action_on_failure: skip
      - match:
          selector: '{job="suricata-logs"}'
          stages:
            - regex:
                expression: '.*'
            - labels:
                event_type: '{{ .event_type }}'
                alert_signature: '{{ .alert_signature }}'
                alert_category: '{{ .alert_category }}'
                alert_severity: '{{ .alert_severity }}'
                src_ip: '{{ .src_ip }}'
                dest_ip: '{{ .dest_ip }}'
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000000-0700"
          fallback_formats:
            - "2006-01-02T15:04:05Z0700"
            - "2006-01-02T15:04:05.999999999Z07:00"
            - "RFC3339"
          action_on_failure: skip
