auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: debug  # ✅ Changed to debug for troubleshooting

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb              # ✅ Changed from boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks
  tsdb_shipper:               # ✅ Changed from boltdb_shipper
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    final_sleep: 0s
    ring:
      kvstore:
        store: inmemory
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_chunk_age: 1h

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  # Timestamp validation
  reject_old_samples: true                   
  reject_old_samples_max_age: 2160h           
  creation_grace_period: 10m                 
  
  # Rate limits
  ingestion_rate_mb: 10                      
  ingestion_burst_size_mb: 20                
  per_stream_rate_limit: 5MB                 
  per_stream_rate_limit_burst: 10MB          
  
  # Label limits
  max_label_name_length: 1024             
  max_label_value_length: 2048        
  max_label_names_per_series: 30      
  max_global_streams_per_user: 10000  
  
  # Query limits
  max_entries_limit_per_query: 5000   
  max_streams_per_user: 0             
  max_query_length: 721h              

chunk_store_config:
  max_look_back_period: 0s

query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
